# Copyright (c) 2026 Chris Corbyn <chris@zizq.io>
# Licensed under the MIT License. See LICENSE file for details.

defmodule Zizq.TLSTest do
  use ExUnit.Case, async: true

  alias Zizq.TLS

  # Real certificates, generated by `openssl` and committed under
  # test/support/tls. Hand-written fixtures would not exercise what
  # `:public_key.pem_decode/1` actually returns, which is where the
  # interesting cases are.
  @dir Path.expand("../support/tls", __DIR__)

  defp path(name), do: Path.join(@dir, name)
  defp pem(name), do: name |> path() |> File.read!()

  defp https, do: URI.parse("https://zizq.internal:7890")

  describe "to_ssl_options/1 with file paths" do
    test "nothing configured produces nothing" do
      assert TLS.to_ssl_options([]) == []
    end

    test "a CA path becomes cacertfile" do
      opts = TLS.to_ssl_options(ca: path("ca.pem"))

      assert opts[:cacertfile] == path("ca.pem")
      refute Keyword.has_key?(opts, :cacerts)
    end

    test "a client identity becomes certfile and keyfile" do
      opts =
        TLS.to_ssl_options(
          client_cert: path("client.pem"),
          client_key: path("client-key.pem")
        )

      assert opts[:certfile] == path("client.pem")
      assert opts[:keyfile] == path("client-key.pem")
    end

    test "paths and PEM can be mixed" do
      opts = TLS.to_ssl_options(ca: pem("ca.pem"), client_cert: path("client.pem"))

      assert is_list(opts[:cacerts])
      assert opts[:certfile] == path("client.pem")
    end
  end

  describe "to_ssl_options/1 with PEM strings" do
    test "a CA becomes DER-encoded cacerts" do
      opts = TLS.to_ssl_options(ca: pem("ca.pem"))

      assert [der] = opts[:cacerts]
      assert is_binary(der)
      refute Keyword.has_key?(opts, :cacertfile)
    end

    test "a client certificate becomes a DER list, so a chain fits" do
      opts = TLS.to_ssl_options(client_cert: pem("client.pem"))

      assert [der] = opts[:cert]
      assert is_binary(der)
    end

    test "a bundle of several certificates keeps all of them" do
      bundle = pem("ca.pem") <> pem("client.pem")

      assert length(TLS.to_ssl_options(ca: bundle)[:cacerts]) == 2
    end

    test "a PKCS#8 key becomes {:PrivateKeyInfo, der}" do
      opts = TLS.to_ssl_options(client_key: pem("client-key.pem"))

      assert {:PrivateKeyInfo, der} = opts[:key]
      assert is_binary(der)
    end

    # OpenSSL writes an `EC PARAMETERS` block before the key itself, so
    # "the first entry that is not a certificate" picks the curve
    # parameters and hands `:ssl` something that is not a key.
    test "an EC key skips the parameters block that precedes it" do
      opts = TLS.to_ssl_options(client_key: pem("ec-key.pem"))

      assert {:ECPrivateKey, der} = opts[:key]
      assert is_binary(der)
    end
  end

  describe "validate!/2" do
    test "accepts an empty configuration" do
      assert TLS.validate!([], https()) == []
    end

    test "accepts a CA on its own, for verifying a private server" do
      assert TLS.validate!([ca: path("ca.pem")], https())
    end

    test "accepts a complete client identity" do
      tls = [client_cert: path("client.pem"), client_key: path("client-key.pem")]

      assert TLS.validate!(tls, https()) == tls
    end

    # Either half alone is silently useless: the handshake proceeds
    # with no client identity and the server's rejection looks
    # unrelated to the configuration that caused it.
    test "rejects a certificate without its key" do
      assert_raise ArgumentError, ~r/:client_cert was given without :client_key/, fn ->
        TLS.validate!([client_cert: path("client.pem")], https())
      end
    end

    test "rejects a key without its certificate" do
      assert_raise ArgumentError, ~r/:client_key was given without :client_cert/, fn ->
        TLS.validate!([client_key: path("client-key.pem")], https())
      end
    end

    test "rejects TLS options on a plain http:// URL" do
      assert_raise ArgumentError, ~r|not https://|, fn ->
        TLS.validate!([ca: path("ca.pem")], URI.parse("http://127.0.0.1:7890"))
      end
    end

    test "rejects a path that does not exist" do
      assert_raise ArgumentError, ~r/neither a PEM string nor a readable file/, fn ->
        TLS.validate!([ca: "/no/such/ca.pem"], https())
      end
    end

    test "rejects a directory given where a file was meant" do
      assert_raise ArgumentError, ~r/neither a PEM string nor a readable file/, fn ->
        TLS.validate!([ca: @dir], https())
      end
    end

    test "rejects PEM that does not decode" do
      assert_raise ArgumentError, ~r/no entries could be decoded/, fn ->
        TLS.validate!([ca: "-----BEGIN CERTIFICATE-----\nnot base64\n"], https())
      end
    end

    test "rejects a CA holding no certificate" do
      assert_raise ArgumentError, ~r/:ca contains no certificate/, fn ->
        TLS.to_ssl_options(ca: pem("client-key.pem"))
      end
    end

    test "rejects a client key holding no private key" do
      assert_raise ArgumentError, ~r/contains no private key/, fn ->
        TLS.to_ssl_options(client_key: pem("ca.pem"))
      end
    end
  end
end
